<div class="site" id="header">
    <div class="container">
        <img src="<?php echo PATH_IMAGE_URL; ?>icon_logo.png">
    </div>
</div>


<div id="menu" class="site" >
    <div class="container">

        <div class="navbar navbar-inverse">
            <div class="navbar-inner">

                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <a class="brand" href="index.php?Ptc/home"><img src="<?php echo PATH_IMAGE_URL; ?>icon_home.png"></a>

                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="index.php?Security/logon">Login</a></li>
                        <li><a href="index.php?Ptc/planos">Planos</a></li>
                        <li ><a href="index.php?Ptc/usuario">Cadastre-se</a></li>
                        <li><a href="index.php?Ptc/parceiros">Parceiros</a></li>
                        <li><a href="index.php?Ptc/contato">Contato</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">