<div id="myCarousel" class="carousel slide"><!-- Carousel  -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner02.jpg">
            </div>
            <div class="item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner01.png">
            </div>
            <div class="item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner03.png">
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- Carousel End -->       


    <div class="row">
        <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteouro.png" class="img-rounded"></p>
            <h2>Ouro</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p>
                <a class="btn" href="#">Ver detalhes »</a>
            </p>
        </div>  
        <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacotebronze.png" class="img-rounded"></p>
            <h2>Bronze</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p>
                <a class="btn" href="#">Ver detalhes »</a>
            </p>
        </div>  
        <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteprata.png" class="img-rounded"></p>
            <h2>Prata</h2>
            <p>Donec id elit non mi porta gravida at eget metus.Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p>
                <a class="btn" href="#">Ver detalhes »</a>
            </p>
        </div>  
    </div>
