<div id="myCarousel" class="carousel slide"><!-- Carousel  -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner02.jpg">
            </div>
            <div class="item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner01.png">
            </div>
            <div class="item">
                <img alt="" src="<?php echo PATH_IMAGE_URL; ?>banner/banner03.png">
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- Carousel End -->       


    <div class="row">
         <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacotebronze.png" class="img-rounded"></p>
            <h2>Bronze</h2>
            <p>Destinado para profissionais com interesse em conhecer o aplicativo, podendo apenas fazer o cadastro de 02 alunos por tempo determinado. </p>
            <p>
                <a class="btn" href="index.php?Ptc/planos">Ver detalhes »</a>
            </p>
        </div>
        <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteprata.png" class="img-rounded"></p>
            <h2>Prata</h2>
            <p>Destinado para profissionais com poucos alunos, podendo fazer o cadastro de 100 alunos por tempo indeterminado. </p>
            <p>
                <a class="btn" href="index.php?Ptc/planos">Ver detalhes »</a>
            </p>
        </div>  
        <div class="span4">
            <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteouro.png" class="img-rounded"></p>
            <h2>Ouro</h2>
            <p>Destinado para profissionais com muitos alunos, sem limite de cadastro de alunos. </p>
            <p>
                <a class="btn" href="index.php?Ptc/planos">Ver detalhes »</a>
            </p>
        </div>  
         
        
    </div>
