<br></br>
<div class="row">
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>f4.png" class="img-rounded"></p>
    </div>  
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>academia.png" class="img-rounded"></p>
    </div>  
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>marceloAmin.png" class="img-rounded"></p>
    </div>  
</div>
<div class="row">
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>plenafforma.png" class="img-rounded"></p>
    </div>  
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>plus.png" class="img-rounded"></p>
    </div>  
    <div class="span4">
        <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>bosco.png" class="img-rounded"></p>
    </div>  
</div>