<br></br>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>
                    <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacotebronze.png" class="img-rounded"></p>
                    <h3 class="text-center">Bronze</h3>
                </th>
                <th>
                    <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteprata.png" class="img-rounded"></p>
                    <h3 class="text-center">Prata</h3>
                </th>
                <th>
                    <p class="text-center"><img src="<?php echo PATH_IMAGE_URL; ?>pacoteouro.png" class="img-rounded"></p>
                    <h3 class="text-center">Ouro</h3>
                </th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
                <td>Recomendação</td>
                <td><p class="text-center"> Para conhecimento do aplicativo.</p></td>
                <td><p class="text-center"> Para profissionais com poucos alunos.</p></td>
                <td><p class="text-center"> Para profissionais com muitos alunos.</p></td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <td>Valor do Plano</td>
                <td><p class="text-center"> Totalmente Gratuito</p></td>
                <td><p class="text-center"> R$ 90,00 mensal</p></td>
                <td><p class="text-center"> R$ 150,00 mensal</p></td>
            </tr>
        </tbody>
        <tbody>
            <tr class="info">
                <td></td>
                <td><p class="text-center"><a class="btn" href="index.php?Ptc/usuario">Contrate</a></p></td>
                <td><p class="text-center"><a class="btn" href="index.php?Ptc/usuario">Contrate</a></p></td>
                <td><p class="text-center"><a class="btn" href="index.php?Ptc/usuario">Contrate</a></p></td>
            </tr>
        </tbody>
    </table>
      
         
        
    </div>
