<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Cadastro<small>Aluno</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Aluno/inserir" method="post">
                
                <input type='hidden' name='idProfessorResponsavel' id='idProfessorResponsavel' value='<?php echo $view_idProfessor; ?>' />
                      
                <h2>Academia*</h2>
                <div class="input-control text">
                    <input type="text" name="academia" id="academia" maxlength="80"/>
                </div>
                
                <h2>Nome Completo*</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" maxlength="115" required=""/>
                </div>
                
                <h2>Data de Nascimento *</h2>
                <div class="input-control text">
                    <input type="text" name="dataNascimento" id="dataNascimento" maxlength="10" style="width: 200px;" required=""/>
                </div>

                <h2>Sexo</h2>
                <label class="input-control radio">
                    <input type="radio" name="sexo" id="sexo" value="F" />
                    <span class="helper">Feminino</span>
                </label>
                <label class="input-control radio">
                    <input type="radio" name="sexo" id="sexo" value="M" />
                    <span class="helper">Masculino</span>
                </label>
                
                <h2>Número Telefone *</h2>
                <div class="input-control text">
                      <input type="text" name="telefone" id="telefone" style="width: 200px;" required=""/>
                </div>
                
                <h2>Endereço *</h2>
                <div class="input-control text">
                    <input type="text" name="endereco" id="endereco" maxlength="115" required=""/>
                </div>
                
                <h2>Email *</h2>
                <div class="input-control text">
                    <input type="text" name="email" id="email" maxlength="115" required=""/>
                </div>
                
                <br/>
                <input type="submit" name="cadastrar" value="Salvar">
            </form>
        </div>
    </div>
</div>