<script type="text/javascript">
    $(function(){
        $('#fCadastro').populate(<?php echo $view_json_objeto; ?>);
    });      
</script>
<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Editar<small>treino</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Treino/atualizar" method="post">

                <input type="hidden" id="id" name="id"/>
                <input type="hidden" id="aluno" name="aluno" value=''/>
                
                <h2>Nome *</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" style="width: 200px;" required=""/>
                </div>
                <h2>Objetivo *</h2>
                <div class="input-control select">
                    <select name="objetivo" id="objetivo" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listObjetivo; ?>
                    </select>
                </div>
                <h2>Data Incial *</h2>
                <div class="input-control text">
                    <input type="text" name="dataTreino" id="dataTreino" style="width: 200px;" />
                </div>
                <h2>Sessões *</h2>
                <div class="input-control text">
                    <input type="text" name="sessoes" id="sessoes" style="width: 200px;" required=""/>
                </div>

        

                <h2>Observações </h2>
                <div class="input-control textarea">
                    <textarea name="observacao" id="observacao" style="width: 820px; height: 100px;" required=""> </textarea>
                </div>                    
                <br/>
                <input type="submit" name="cadastrar" value="Salvar">
            </form>
        </div>
    </div>
</div>