<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Cadastro<small>Exercicio</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <form name="fCadastro" id="fCadastro" action="index.php?Exercicio/inserir" method="post">
                <h2>Nome *</h2>
                <div class="input-control text">
                    <input type="text" name="nome" id="nome" maxlength="115" required=""/>
                </div>
                <h2>Grupo Muscular *</h2>
                <div class="input-control select">
                    <select name="grupoMuscular" id="grupoMuscular" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listGrupoMuscular; ?>
                    </select>
                </div>
                <br/>
                <input type="submit" value="Salvar">
            </form>
        </div>
    </div>
</div>