<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Perfil<small>Informações</small></h1>
            <a href="javascript:history.go(-1)" class="back-button big page-back"></a>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
            <?php echo $view_toolbar; ?>
            <div class="page-control" data-role="page-control">
                <ul>
                    <li class="active"><a href="#frameI">Identificação</a></li>
                </ul>
                <div class="frames">
                    
                    <div class="frame active" id="frameI">
                        <h2>Nome: </h2>
                        <?php echo $view_professor->getNome(); ?>
                        <h2>Sexo</h2>
                        <?php echo $view_professor->getSexo(); ?>
                        <h2>Número Telefone: </h2>
                        <?php echo FormatHelper::formatTelefone($view_professor->getTelefone()); ?>
                        <h2>Endereço: </h2>
                        <?php echo $view_professor->getEndereco(); ?>
                        <h2>Email: </h2>
                        <?php echo $view_professor->getEmail(); ?>                        
                    </div>                                    
                    
                </div>
            </div>
        </div>
    </div>
</div>